Api/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="Api"

urlpatterns = [
    path('', views.home,name="search"),
    path('getVedios/<str:key>/', views.getMessages, name='getV'),    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from Api.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('api/', include('Api.urls', namespace='Api'), name='Api'),

]

Api/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
import uuid

class Vedio(models.Model):
    id = models.AutoField(primary_key=True)
    key=models.CharField(max_length=20050, null=True)
    date=models.DateField(auto_now=False, auto_now_add=False)
    link = models.CharField(max_length=20050, null=True)
    title = models.CharField(max_length=10000, blank=True, null=True)
    description=models.CharField(max_length=10000, blank=True, null=True)
    def __str__(self):
        return str(self.title)

Api/views.py
from django.shortcuts import render
from django.conf import settings
from .models import *
import requests
from django.http import HttpResponse, JsonResponse, Http404


# Create your views here.

def home(request):
    if request.method=="POST":
        search_url='https://www.googleapis.com/youtube/v3/search'
        params={
            'part' :'snippet',
            'q' : request.POST.get('keyword'),
            'key' : settings.YOUTUBE_DATA_API_KEY,
            'maxResults': 9
        }
        r=requests.get(search_url,params=params)
        results=r.json()['items']
        print(len(results))
        for result in results:
            try:
                a='https://www.youtube.com/embed/'+result['id']['videoId']
                v=Vedio.objects.create(link=a,title=result['snippet']['title'],description=result['snippet']['description'])
                v.save()
                print(v)
            except:
                pass
        msg='Search Successfull!!'
        context={
            'msg':msg,
            'vedio':Vedio.objects.all()   
        }
        return render (request,'base.html', context)
    else:
        return render(request,'base.html')

def getMessages(request, key):
    print(key)
    print('hghgf')
    search_url='https://www.googleapis.com/youtube/v3/search'
    params={
        'part' :'snippet',
        'q' : key,
        'key' : settings.YOUTUBE_DATA_API_KEY,
        'maxResults': 9
    }
    r=requests.get(search_url,params=params)
    print(r)
    results=r.json()['items']
    print(results)
    length=0
    try:   
        length=len(Vedio.objects.filter(key=key))
    except:
        pass
    print(length)
    if length<100:
        for result in results:
            # try:
            a='https://www.youtube.com/embed/'+result['id']['videoId']
            v=Vedio.objects.create(key=key,link=a,title=result['snippet']['title'],date=str(result['snippet']['publishedAt'])[:10],description=result['snippet']['description'])
            v.save()
            print(v)
            # except:
            #     pass
        print('success')
        print(Vedio.objects.filter(key=key))
        # msg='Search Successfull!!'
        # context={
        #     'msg':msg,
        #     'vedio':Vedio.objects.all()   
        # }


    print(list(Vedio.objects.filter(key=key).order_by('date').values()))
    return JsonResponse({"messages":list(Vedio.objects.filter(key=key).order_by('date').values())})

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Document</title>
    <style>
        @import url(//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css);

        .card .card-image {
            overflow: hidden;
            -webkit-transform-style: preserve-3d;
            -moz-transform-style: preserve-3d;
            -ms-transform-style: preserve-3d;
            -o-transform-style: preserve-3d;
            transform-style: preserve-3d;
        }


        .card {
            margin-top: 10px;
            position: relative;
            -webkit-box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
            -moz-box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
            box-shadow: 4 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
        }

        .card .card-content {
            padding: 10px;

        }

        .card .card-content .card-title,
        .card-reveal .card-title {
            font-size: 20px;
            font-weight: 100;
            margin-bottom: 10px;
        }

        .container .content {
            position: absolute;
            bottom: 0;
            background: rgba(0, 0, 0, 0.5);
            /* Black background with transparency */
            color: #f1f1f1;
            width: 80%;
            padding: 2px;
            text-align: right;
            margin-left: 90px;
            padding-right: 15px;

        }
    </style>
</head>

<body>


    <h1 class="display-4 text-center">Youtube Search</h1>
    {% if msg%}
    <p class="lead">
        {{ msg }}
    </p>
    {% endif %}
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Api Search!</h4>
        <p>This Website searches for default keyword 'music' and displays the content. Intially only 9 vedios willbe there but the page make GET requests after 2 min. The vedios are arranged according to accessending order of 'publishedAt' value </p>
        <hr>
        <p class="mb-0">When There will be 100 vedio of the keyword 'music' the server will stop fetching data.</p>
      </div>
    <form action="{% url 'Api:search' %}" method="POST" style="display:none">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Search For</label>
            <input type="keyword" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                default='music'>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>




    <div class="container">
        {% comment %} {% for r in vedio %} {% endcomment %}
        <div class="row" id="display">

        </div>
        {% comment %} {% endfor %} {% endcomment %}


        <!--end row-->

    </div>
    <!--end container-->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"
        integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
    <script>
        $(function () {

            $('#show').on('click', function () {
                $('.card-reveal').slideToggle('slow');
            });

            $('.card-reveal .close').on('click', function () {
                $('.card-reveal').slideToggle('slow');
            });
        });
    </script>
</body>
<script>

console.log('sdfsdfsdfdsf');
            var a = document.getElementById('exampleInputEmail1').value;
            if (a == '')
                a = 'music'
            $.ajax({
                type: 'GET',
                url: "{% url 'Api:getV' key='music' %}",
                //`/Api/getVedios/${a}/`,
                success: function (response) {
                    console.log(response);
                    $("#display").empty();
                    

                    for (var key in response.messages) {
                        var temp;
                        temp = "<div class='col-md-6'>"+"<div class='card-image'>"+"<div class='embed-responsive embed-responsive-16by9'>"+`<iframe width="280" height="157" src="${response.messages[key].link}" frameborder="0" allowfullscreen></iframe>`+"</div></div><div class='card-content'>"+`<span class="display-4">${response.messages[key].title}</span><p class="ard-title">${response.messages[key].description}</p>`+"</div></div></div>";
                        count++;
                        console.log($("#display").childElementCount)
                        $("#display").append(temp);
                    }
                    
                },
                error: function (response) {
                    alert('An error occured')
                }
                
            });
    $(document).ready(function () {
        count = document.getElementById('display').childElementCount;
        if (count<=100)
        {
            document.getElementById('display').clearChildren
            setInterval(function () {
            console.log('sdfsdfsdfdsf');
            var a = document.getElementById('exampleInputEmail1').value;
            if (a == '')
                a = 'music'
            $.ajax({
                type: 'GET',
                url: "{% url 'Api:getV' key='music' %}",
                //`/Api/getVedios/${a}/`,
                success: function (response) {
                    console.log(response);
                    $("#display").empty();
                    count = 0;

                    for (var key in response.messages) {
                        var temp;
                        temp = "<div class='col-md-6'>"+"<div class='card-image'>"+"<div class='embed-responsive embed-responsive-16by9'>"+`<iframe width="280" height="157" src="${response.messages[key].link}" frameborder="0" allowfullscreen></iframe>`+"</div></div><div class='card-content'>"+`<span class="display-4">${response.messages[key].title}</span><p class="ard-title">${response.messages[key].description}</p>`+"</div></div></div>";
                        count++;
                        console.log($("#display").childElementCount)
                        $("#display").append(temp);
                    }
                    
                },
                error: function (response) {
                    alert('An error occured')
                }
                
            });
            
        }, 200000);
        }
        
    })
</script>

</html>